seed: 1

defaults:
  - _self_  # Override values within this file with values in selected files.


input:
  batch_size: 128
  dino_processed: False
  ceil_input: False


training:
  continue_train: False
  val_idx: 0  # x > 0: validate every x steps; otherwise, no validation.

  learning_rate: 1e-3

  learning_rate_schedule: 1  # 0 - constant lr; 1 - linear warm-up.
  warmup_steps: 1000
  lr_decay: 1.0
  decay_log: 1000
  gradient_clip: 0.1  # x > 0 clipping gradient norm to given value; otherwise, no clipping.
  weight_decay: 0
  print_idx: 1000  # x > 0: print metrics every x steps; otherwise, no printing.
  save_idx: 5000

evaluation:
  magnitude_mask_threshold: 0.1  # Features with magnitudes below this threshold are masked out during evaluation.
  out: False
  load_file: ./outputs/Tetro_Gray1_Lv1/2025-02-28_17-52-46/3_Gray_1_Lv1_Step55000.pt
  test: False
hydra:
  run:
    dir: ./outputs/${hydra.runtime.choices.experiment}/${now:%Y-%m-%d_%H-%M-%S}


