name: RotatingFeatures
channels:
  - defaults
dependencies:
  - python=3.8
  - scikit-image
  - scikit-learn
  - seaborn
  - tensorflow
  - numpy
  - scipy
  - matplotlib
  - pandas
  - tqdm

## Pip install
#  - hydra-core
#  - einops


## Cuda Pytorch
#conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
